[settings]
DOWNLOAD_DELAY = 1
RANDOMIZE_DOWNLOAD_DELAY = true
LOG_ENABLED = false
REQUEST_FINGERPRINTER_IMPLEMENTATION = "2.7"

[toscrape]
name = "toscrape"
headers.Accept = "text/html; charset=utf-8"
start_url = "https://quotes.toscrape.com/page/1/"
output.root_path = "/app/output"